// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payee.proto

package payeeService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchPayeeByPhoneRequest struct {
	Phone                []string `protobuf:"bytes,1,rep,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchPayeeByPhoneRequest) Reset()         { *m = FetchPayeeByPhoneRequest{} }
func (m *FetchPayeeByPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*FetchPayeeByPhoneRequest) ProtoMessage()    {}
func (*FetchPayeeByPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3678d4ab00f1cb, []int{0}
}

func (m *FetchPayeeByPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPayeeByPhoneRequest.Unmarshal(m, b)
}
func (m *FetchPayeeByPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPayeeByPhoneRequest.Marshal(b, m, deterministic)
}
func (m *FetchPayeeByPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPayeeByPhoneRequest.Merge(m, src)
}
func (m *FetchPayeeByPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_FetchPayeeByPhoneRequest.Size(m)
}
func (m *FetchPayeeByPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPayeeByPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPayeeByPhoneRequest proto.InternalMessageInfo

func (m *FetchPayeeByPhoneRequest) GetPhone() []string {
	if m != nil {
		return m.Phone
	}
	return nil
}

type FetchPayeeByPhoneNumbersResponse struct {
	Payees               []*FetchPayeeByPhoneResponse `protobuf:"bytes,1,rep,name=payees,proto3" json:"payees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FetchPayeeByPhoneNumbersResponse) Reset()         { *m = FetchPayeeByPhoneNumbersResponse{} }
func (m *FetchPayeeByPhoneNumbersResponse) String() string { return proto.CompactTextString(m) }
func (*FetchPayeeByPhoneNumbersResponse) ProtoMessage()    {}
func (*FetchPayeeByPhoneNumbersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3678d4ab00f1cb, []int{1}
}

func (m *FetchPayeeByPhoneNumbersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPayeeByPhoneNumbersResponse.Unmarshal(m, b)
}
func (m *FetchPayeeByPhoneNumbersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPayeeByPhoneNumbersResponse.Marshal(b, m, deterministic)
}
func (m *FetchPayeeByPhoneNumbersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPayeeByPhoneNumbersResponse.Merge(m, src)
}
func (m *FetchPayeeByPhoneNumbersResponse) XXX_Size() int {
	return xxx_messageInfo_FetchPayeeByPhoneNumbersResponse.Size(m)
}
func (m *FetchPayeeByPhoneNumbersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPayeeByPhoneNumbersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPayeeByPhoneNumbersResponse proto.InternalMessageInfo

func (m *FetchPayeeByPhoneNumbersResponse) GetPayees() []*FetchPayeeByPhoneResponse {
	if m != nil {
		return m.Payees
	}
	return nil
}

type FetchPayeeByPhoneResponse struct {
	PersonId             string   `protobuf:"bytes,1,opt,name=personId,proto3" json:"personId,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchPayeeByPhoneResponse) Reset()         { *m = FetchPayeeByPhoneResponse{} }
func (m *FetchPayeeByPhoneResponse) String() string { return proto.CompactTextString(m) }
func (*FetchPayeeByPhoneResponse) ProtoMessage()    {}
func (*FetchPayeeByPhoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb3678d4ab00f1cb, []int{2}
}

func (m *FetchPayeeByPhoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPayeeByPhoneResponse.Unmarshal(m, b)
}
func (m *FetchPayeeByPhoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPayeeByPhoneResponse.Marshal(b, m, deterministic)
}
func (m *FetchPayeeByPhoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPayeeByPhoneResponse.Merge(m, src)
}
func (m *FetchPayeeByPhoneResponse) XXX_Size() int {
	return xxx_messageInfo_FetchPayeeByPhoneResponse.Size(m)
}
func (m *FetchPayeeByPhoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPayeeByPhoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPayeeByPhoneResponse proto.InternalMessageInfo

func (m *FetchPayeeByPhoneResponse) GetPersonId() string {
	if m != nil {
		return m.PersonId
	}
	return ""
}

func (m *FetchPayeeByPhoneResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *FetchPayeeByPhoneResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *FetchPayeeByPhoneResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchPayeeByPhoneRequest)(nil), "payee.FetchPayeeByPhoneRequest")
	proto.RegisterType((*FetchPayeeByPhoneNumbersResponse)(nil), "payee.FetchPayeeByPhoneNumbersResponse")
	proto.RegisterType((*FetchPayeeByPhoneResponse)(nil), "payee.FetchPayeeByPhoneResponse")
}

func init() {
	proto.RegisterFile("payee.proto", fileDescriptor_eb3678d4ab00f1cb)
}

var fileDescriptor_eb3678d4ab00f1cb = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x48, 0xac, 0x4c,
	0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x0c, 0xb8, 0x24, 0xdc,
	0x52, 0x4b, 0x92, 0x33, 0x02, 0x40, 0x3c, 0xa7, 0xca, 0x80, 0x8c, 0xfc, 0xbc, 0xd4, 0xa0, 0xd4,
	0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x11, 0x2e, 0xd6, 0x02, 0x10, 0x5f, 0x82, 0x51, 0x81, 0x59,
	0x83, 0x33, 0x08, 0xc2, 0x51, 0x8a, 0xe1, 0x52, 0xc0, 0xd0, 0xe1, 0x57, 0x9a, 0x9b, 0x94, 0x5a,
	0x54, 0x1c, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64, 0xc1, 0xc5, 0x06, 0x36, 0xbe,
	0x18, 0xac, 0x95, 0xdb, 0x48, 0x41, 0x0f, 0x62, 0x35, 0x16, 0xab, 0x20, 0x3a, 0x82, 0xa0, 0xea,
	0x95, 0xda, 0x19, 0xb9, 0x24, 0x71, 0xaa, 0x12, 0x92, 0xe2, 0xe2, 0x28, 0x48, 0x2d, 0x2a, 0xce,
	0xcf, 0xf3, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x11, 0xae, 0x65, 0x02,
	0x4b, 0x40, 0x38, 0x42, 0x32, 0x5c, 0x9c, 0x69, 0x99, 0x45, 0xc5, 0x25, 0x7e, 0x89, 0xb9, 0xa9,
	0x12, 0xcc, 0x60, 0x19, 0x84, 0x00, 0xc8, 0xbc, 0x9c, 0x44, 0xa8, 0x24, 0x0b, 0xc4, 0x3c, 0x18,
	0xdf, 0xa8, 0x94, 0x8b, 0x07, 0xec, 0x86, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0xa1, 0x54,
	0x2e, 0x71, 0xf7, 0xd4, 0x12, 0xb0, 0x50, 0x31, 0xaa, 0xb7, 0x85, 0xe4, 0x71, 0x7b, 0x0f, 0x1c,
	0x92, 0x52, 0xea, 0xb8, 0x14, 0xa0, 0x05, 0x9c, 0x12, 0x83, 0x13, 0x5f, 0x14, 0x4f, 0x01, 0x92,
	0xb5, 0x49, 0x6c, 0xe0, 0xe8, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x98, 0xf7, 0xf5, 0xf5,
	0xbd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PayeeServiceClient is the client API for PayeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayeeServiceClient interface {
	GetPayeesByPhoneNumbers(ctx context.Context, in *FetchPayeeByPhoneRequest, opts ...grpc.CallOption) (*FetchPayeeByPhoneNumbersResponse, error)
}

type payeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPayeeServiceClient(cc grpc.ClientConnInterface) PayeeServiceClient {
	return &payeeServiceClient{cc}
}

func (c *payeeServiceClient) GetPayeesByPhoneNumbers(ctx context.Context, in *FetchPayeeByPhoneRequest, opts ...grpc.CallOption) (*FetchPayeeByPhoneNumbersResponse, error) {
	out := new(FetchPayeeByPhoneNumbersResponse)
	err := c.cc.Invoke(ctx, "/payee.PayeeService/GetPayeesByPhoneNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayeeServiceServer is the server API for PayeeService service.
type PayeeServiceServer interface {
	GetPayeesByPhoneNumbers(context.Context, *FetchPayeeByPhoneRequest) (*FetchPayeeByPhoneNumbersResponse, error)
}

// UnimplementedPayeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPayeeServiceServer struct {
}

func (*UnimplementedPayeeServiceServer) GetPayeesByPhoneNumbers(ctx context.Context, req *FetchPayeeByPhoneRequest) (*FetchPayeeByPhoneNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayeesByPhoneNumbers not implemented")
}

func RegisterPayeeServiceServer(s *grpc.Server, srv PayeeServiceServer) {
	s.RegisterService(&_PayeeService_serviceDesc, srv)
}

func _PayeeService_GetPayeesByPhoneNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPayeeByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeeServiceServer).GetPayeesByPhoneNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payee.PayeeService/GetPayeesByPhoneNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeeServiceServer).GetPayeesByPhoneNumbers(ctx, req.(*FetchPayeeByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payee.PayeeService",
	HandlerType: (*PayeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayeesByPhoneNumbers",
			Handler:    _PayeeService_GetPayeesByPhoneNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payee.proto",
}
