version: "3.0"

services:
  eventstore:
    image: apachepulsar/pulsar:2.6.1
    container_name: eventstore
    restart: on-failure
    ports:
      - 6650:6650
      - 8090:8080
    command: bin/pulsar standalone

    mongodb:
      image: mongo:4.2.9
      container_name: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: roava
      volumes:
        - "${HOME}/mnt/datastore/mongo:/data/db"
      ports:
        - 27018:27017

  ms.onboarding:
    container_name: ms.onboarding
    image: eu.gcr.io/roava-io/roava.io/services/ms.onboarding:0.4.8
    restart: on-failure
    environment:
      #PULSAR_TLS_CERT: `cat ./pulsar.pem`
      SERVICE_NAME: ms.onboarding
      PORT: 2000
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: local
      PULSAR_URL: pulsar://host.docker.internal:6650
      JWT_SECRET: localSecret
    depends_on:
      #- mongodb
      - eventstore
    ports:
      - 2000:2000

  ms.cdd:
    container_name: ms.aml
    image: eu.gcr.io/roava-io/roava.io/services/ms.cdd:0.3.1
    restart: on-failure
    environment:
      SERVICE_NAME: ms.cdd
      PORT: 2001
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: local
      PULSAR_URL: pulsar://host.docker.internal:6650
    depends_on:
      #- mongodb
      - eventstore
    ports:
      - 2001:2001

  ms.verify:
    container_name: ms.verify
    image: eu.gcr.io/roava-io/roava.io/services/ms.verify:0.1.9
    restart: on-failure
    environment:
      PORT: 2002
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: local
      PULSAR_URL: pulsar://host.docker.internal:6650
      # PULSAR_TLS_CERT=`cat ./pulsar.pem`
      SERVICE_NAME: ms.verify
    depends_on:
      #- mongodb
      - eventstore
    ports:
      - 2002:2002

  ms.auth:
    container_name: ms.auth
    image: eu.gcr.io/roava-io/roava.io/services/ms.auth:0.2.3
    restart: on-failure
    environment:
      SERVICE_NAME: ms.auth
      PORT: 2003
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: local
      PULSAR_URL: pulsar://host.docker.internal:6650
      JWT_SECRET: localSecret
    depends_on:
      #- mongodb
      - eventstore
    ports:
      - 2003:2003

  accounts:
    container_name: accounts
    image: eu.gcr.io/roava-io/roava.io/services/accounts:0.3.0
    restart: on-failure
    environment:
      SERVICE_NAME: accounts
      PORT: 2004
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: dev
      PULSAR_URL: pulsar://host.docker.internal:6650
      MAMBU_BASE_URL: https://roava.sandbox.mambu.com/api
      MAMBU_API_KEY: ezQqvMOuSCH4oHh9WtJGi4AAZyyYAqSx
      NGN_PRODUCT_ID:
      GBP_PRODUCT_ID:
      ASSIGNED_BRANCH_ID:
      HTTPPORT: 20004
      BVN_BASE_URL: https://api.fcmb.com/fcmb/test/v1
      BVN_KEY: e28b0b19-19da-4672-9168-40c263e1a02d
      FCMB_BASE_URL: https://uat.firstcitygrouponline.com/onlineaccountopeningservice/api
      FCMB_KEY: 123456
      FCMB_ID: 12345
      FCMB_SCHEME:
    depends_on:
      #- mongodb
      - eventstore
    ports:
      - 2004:2004

  payments:
    container_name: payments
    image: eu.gcr.io/roava-io/roava.io/services/ms.payment:0.1.5
    restart: on-failure
    environment:
      SERVICE_NAME: payments
      PORT: 2005
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: local
      PULSAR_URL: pulsar://host.docker.internal:6650
    depends_on:
      #- mongodb
      - eventstore
    ports:
      - 2005:2005

  ms.person:
    container_name: ms.person
    image: eu.gcr.io/roava-io/roava.io/services/ms.person:0.3.6
    restart: on-failure
    environment:
      SERVICE_NAME: ms.person
      PORT: 2006
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: local
      PULSAR_URL: pulsar://host.docker.internal:6650
    depends_on:
      #- mongodb
      - eventstore
    ports:
      - 2006:2006

  ms.identity:
    container_name: ms.identity
    image: eu.gcr.io/roava-io/roava.io/services/ms.identity:0.2.5
    restart: on-failure
    environment:
      SERVICE_NAME: ms.identity
      PORT: 2007
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: local
      PULSAR_URL: pulsar://host.docker.internal:6650
    depends_on:
      #- mongodb
      - eventstore
    ports:
      - 2007:2007

  api:
    container_name: api
    build:
      context: ./
    environment:
      SERVICE_NAME: ms.api
      PORT: 9000
      DATABASE_URL: mongodb://root:root@host.docker.internal:27018
      DATABASE_NAME: roava
      ENVIRONMENT: local
      PULSAR_URL: pulsar://host.docker.internal:6650
      ONBOARDING_SERVICE_URL: ms.onboarding:2000
      CDD_SERVICE_URL: ms.cdd:2001
      VERIFY_SERVICE_URL: ms.verify:2002
      AUTH_SERVICE_URL: ms.auth:2003
      ACCOUNT_SERVICE_URL: accounts:2004
      PAYMENT_SERVICE_URL: payments:2005
      PERSON_SERVICE_URL: ms.person:2006
      IDENTITY_SERVICE_URL: ms.identity:2007
    depends_on:
      - ms.onboarding
      - ms.cdd
      - ms.verify
      - ms.auth
      - accounts
      - payments
      - ms.person
      - ms.identity
    ports:
      - 9000:9000
    restart: on-failure
