SERVICE_NAME: "ms.api"
PORT: "2000"
mongodb_uri: "mongodb://127.0.0.1:27017"
pulsar_url: "pulsar://127.0.0.1:6650"
pulsar_cert: ""
HTTP_PORT: "8000"

onboarding_service_url: ""
verification_service_url: ""
auth_service_url: "localhost:4000"
account_service_url: ""
customer_service_url: ""
payment_service_url: "localhost:3002"
pricing_service_url: ""
messaging_service_url: ""