SERVICE_NAME: "ms.api"
PORT: "2000"
mongodb_uri: "mongodb://localhost:27017"
pulsar_url: "pulsar://10.0.0.2:6650"
pulsar_cert: ""
HTTP_PORT: 8000

cdd_service_url: ""
onfido_service_url: ""
kyc_service_url: ""
onboarding_service_url: ""
verify_service_url: ""
auth_service_url: "127.0.0.1:2010"
account_service_url: ""
payee_service_url: ""
person_service_url: ""
payment_service_url: "127.0.0.1:2012"
identity_service_url: ""
pricing_service_url: ""
JWT_SECRETS: ""
redis_url: ""
redis_password: ""

bvn:
  key: ""
  url: ""

complyadvantage:
  signed_branch_id: ""
  key: ""
  risk_profile_id: ""
  url: ""

mambu:
  key: ""
  url: ""

onfido:
  token: ""
  application_id: ""

postcoder:
  key: ""

postmark:
  key: ""

twilio:
  sid: ""
  token: ""
