apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-api
      backend: ms-onboarding
      backend: ms-verify
      backend: ms-auth
      #backend: ms-cdd

  template:
    metadata:
      labels:
        app: ms-api
        backend: ms-onboarding
        backend: ms-verify
        backend: ms-auth
        #backend: ms-cdd

    spec:
      containers:
      # [START esp]
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:2
        args: [
          "--listener_port=8081",
          "--backend=127.0.0.1:9000",
          "--service=develop.roava.io",
          "--rollout_strategy=managed",
          "--enable_debug"
        ]
      # [END esp]
        ports:
          - containerPort: 8081

      - image: eu.gcr.io/roava-io/roava.io/services/ms.api:0.4.7
        imagePullPolicy: Always
        tag:
        name: ms-api
        ports:
        - name: ms-api
          containerPort: 9000

        env:
        - name: PORT
          value: "9000"
        - name: ONBOARDING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: onboarding-service-url
        - name: PERSON_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: person-service-url
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: payment-service-url
        - name: PAYEE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: payee-service-url

        - name: VERIFY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: verify-service-url
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: auth-service-url
        - name: ONFIDO_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: onfido-service-url
        - name: KYC_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: kyc-service-url

        - name: CDD_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: cdd_service_url
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: product-service-url
        - name: SERVICE_NAME
          value: ms.api
        - name: IDENTITY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: config-data
              key: identity-service-url
