// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	paymentService "ms.api/protos/pb/paymentService"

	types "ms.api/protos/pb/types"
)

// PaymentServiceClient is an autogenerated mock type for the PaymentServiceClient type
type PaymentServiceClient struct {
	mock.Mock
}

// CreatePayee provides a mock function with given fields: ctx, in, opts
func (_m *PaymentServiceClient) CreatePayee(ctx context.Context, in *paymentService.CreatePayeeRequest, opts ...grpc.CallOption) (*types.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *types.Response
	if rf, ok := ret.Get(0).(func(context.Context, *paymentService.CreatePayeeRequest, ...grpc.CallOption) *types.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *paymentService.CreatePayeeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeTransfer provides a mock function with given fields: ctx, in, opts
func (_m *PaymentServiceClient) MakeTransfer(ctx context.Context, in *paymentService.TransferRequest, opts ...grpc.CallOption) (*paymentService.SuccessResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *paymentService.SuccessResponse
	if rf, ok := ret.Get(0).(func(context.Context, *paymentService.TransferRequest, ...grpc.CallOption) *paymentService.SuccessResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentService.SuccessResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *paymentService.TransferRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
