// Code generated by protoc-gen-go. DO NOT EDIT.
// source: onfido.proto

package onfidoService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee556dc27182966, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type ApplicantSDKTokenRequest struct {
	ApplicantId          string   `protobuf:"bytes,1,opt,name=applicantId,proto3" json:"applicantId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicantSDKTokenRequest) Reset()         { *m = ApplicantSDKTokenRequest{} }
func (m *ApplicantSDKTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicantSDKTokenRequest) ProtoMessage()    {}
func (*ApplicantSDKTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee556dc27182966, []int{1}
}

func (m *ApplicantSDKTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicantSDKTokenRequest.Unmarshal(m, b)
}
func (m *ApplicantSDKTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicantSDKTokenRequest.Marshal(b, m, deterministic)
}
func (m *ApplicantSDKTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicantSDKTokenRequest.Merge(m, src)
}
func (m *ApplicantSDKTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ApplicantSDKTokenRequest.Size(m)
}
func (m *ApplicantSDKTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicantSDKTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicantSDKTokenRequest proto.InternalMessageInfo

func (m *ApplicantSDKTokenRequest) GetApplicantId() string {
	if m != nil {
		return m.ApplicantId
	}
	return ""
}

type ApplicantSDKTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicantSDKTokenResponse) Reset()         { *m = ApplicantSDKTokenResponse{} }
func (m *ApplicantSDKTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicantSDKTokenResponse) ProtoMessage()    {}
func (*ApplicantSDKTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee556dc27182966, []int{2}
}

func (m *ApplicantSDKTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicantSDKTokenResponse.Unmarshal(m, b)
}
func (m *ApplicantSDKTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicantSDKTokenResponse.Marshal(b, m, deterministic)
}
func (m *ApplicantSDKTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicantSDKTokenResponse.Merge(m, src)
}
func (m *ApplicantSDKTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ApplicantSDKTokenResponse.Size(m)
}
func (m *ApplicantSDKTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicantSDKTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicantSDKTokenResponse proto.InternalMessageInfo

func (m *ApplicantSDKTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type OnfidoCheckWebhookRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CompletedAt          string   `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnfidoCheckWebhookRequest) Reset()         { *m = OnfidoCheckWebhookRequest{} }
func (m *OnfidoCheckWebhookRequest) String() string { return proto.CompactTextString(m) }
func (*OnfidoCheckWebhookRequest) ProtoMessage()    {}
func (*OnfidoCheckWebhookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee556dc27182966, []int{3}
}

func (m *OnfidoCheckWebhookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnfidoCheckWebhookRequest.Unmarshal(m, b)
}
func (m *OnfidoCheckWebhookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnfidoCheckWebhookRequest.Marshal(b, m, deterministic)
}
func (m *OnfidoCheckWebhookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnfidoCheckWebhookRequest.Merge(m, src)
}
func (m *OnfidoCheckWebhookRequest) XXX_Size() int {
	return xxx_messageInfo_OnfidoCheckWebhookRequest.Size(m)
}
func (m *OnfidoCheckWebhookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnfidoCheckWebhookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnfidoCheckWebhookRequest proto.InternalMessageInfo

func (m *OnfidoCheckWebhookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OnfidoCheckWebhookRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OnfidoCheckWebhookRequest) GetCompletedAt() string {
	if m != nil {
		return m.CompletedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Void)(nil), "onfido.void")
	proto.RegisterType((*ApplicantSDKTokenRequest)(nil), "onfido.ApplicantSDKTokenRequest")
	proto.RegisterType((*ApplicantSDKTokenResponse)(nil), "onfido.ApplicantSDKTokenResponse")
	proto.RegisterType((*OnfidoCheckWebhookRequest)(nil), "onfido.onfidoCheckWebhookRequest")
}

func init() {
	proto.RegisterFile("onfido.proto", fileDescriptor_eee556dc27182966)
}

var fileDescriptor_eee556dc27182966 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x6d, 0xf2, 0x7d, 0x06, 0x9c, 0xa6, 0x0a, 0x8b, 0x48, 0xd2, 0x53, 0x9a, 0x93, 0xa7, 0x82,
	0x7a, 0xf5, 0x60, 0xd5, 0x8b, 0x78, 0x50, 0x5a, 0x41, 0xf0, 0x22, 0x49, 0x76, 0x6a, 0x96, 0xd4,
	0x9d, 0x35, 0x3b, 0xa9, 0xbf, 0xcc, 0xff, 0x27, 0x66, 0x93, 0x52, 0xd0, 0x7a, 0x7c, 0x6f, 0xe6,
	0xf1, 0xde, 0x9b, 0x81, 0x90, 0xf4, 0x52, 0x49, 0x9a, 0x9a, 0x9a, 0x98, 0x44, 0xe0, 0x50, 0x1a,
	0xc0, 0xff, 0x35, 0x29, 0x99, 0x5e, 0x40, 0x34, 0x33, 0x66, 0xa5, 0x8a, 0x4c, 0xf3, 0xe2, 0xe6,
	0xee, 0x91, 0x2a, 0xd4, 0x73, 0x7c, 0x6f, 0xd0, 0xb2, 0x48, 0x60, 0x98, 0xf5, 0xb3, 0x5b, 0x19,
	0x79, 0x89, 0x77, 0xb2, 0x3f, 0xdf, 0xa6, 0xd2, 0x53, 0x88, 0x7f, 0x51, 0x5b, 0x43, 0xda, 0xa2,
	0x38, 0x82, 0x3d, 0xfe, 0x26, 0x3a, 0xa1, 0x03, 0xe9, 0x12, 0x62, 0x17, 0xe1, 0xba, 0xc4, 0xa2,
	0x7a, 0xc2, 0xbc, 0x24, 0xaa, 0x7a, 0xc7, 0x03, 0xf0, 0x55, 0x6f, 0xe4, 0x2b, 0x29, 0x8e, 0x21,
	0xb0, 0x9c, 0x71, 0x63, 0x23, 0xbf, 0xe5, 0x3a, 0x24, 0x26, 0x10, 0x16, 0xf4, 0x66, 0x56, 0xc8,
	0x28, 0x5f, 0x32, 0x8e, 0xfe, 0xb9, 0x68, 0x1b, 0x6e, 0xc6, 0x67, 0x9f, 0x1e, 0x8c, 0xee, 0x5b,
	0xa3, 0x05, 0xd6, 0x6b, 0x55, 0xa0, 0xc8, 0x21, 0x7e, 0x45, 0x8d, 0x75, 0xc6, 0xf8, 0x23, 0xb4,
	0x48, 0xa6, 0xdd, 0x99, 0x76, 0x5d, 0x63, 0x3c, 0xf9, 0x63, 0xc3, 0x35, 0x4e, 0x07, 0xe2, 0x12,
	0x86, 0x1f, 0xae, 0xd2, 0x43, 0x63, 0x4b, 0xb1, 0xd1, 0xec, 0xac, 0x3c, 0x0e, 0xfb, 0x95, 0xf6,
	0x1d, 0x83, 0xab, 0xc3, 0xe7, 0x11, 0x6d, 0xc7, 0xce, 0x83, 0xf6, 0x71, 0xe7, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xa7, 0x0d, 0x5b, 0xfe, 0xc8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OnfidoServiceClient is the client API for OnfidoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnfidoServiceClient interface {
	GenerateApplicantSDKToken(ctx context.Context, in *ApplicantSDKTokenRequest, opts ...grpc.CallOption) (*ApplicantSDKTokenResponse, error)
	WebhookPush(ctx context.Context, in *OnfidoCheckWebhookRequest, opts ...grpc.CallOption) (*Void, error)
}

type onfidoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnfidoServiceClient(cc grpc.ClientConnInterface) OnfidoServiceClient {
	return &onfidoServiceClient{cc}
}

func (c *onfidoServiceClient) GenerateApplicantSDKToken(ctx context.Context, in *ApplicantSDKTokenRequest, opts ...grpc.CallOption) (*ApplicantSDKTokenResponse, error) {
	out := new(ApplicantSDKTokenResponse)
	err := c.cc.Invoke(ctx, "/onfido.OnfidoService/generateApplicantSDKToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onfidoServiceClient) WebhookPush(ctx context.Context, in *OnfidoCheckWebhookRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/onfido.OnfidoService/webhookPush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnfidoServiceServer is the server API for OnfidoService service.
type OnfidoServiceServer interface {
	GenerateApplicantSDKToken(context.Context, *ApplicantSDKTokenRequest) (*ApplicantSDKTokenResponse, error)
	WebhookPush(context.Context, *OnfidoCheckWebhookRequest) (*Void, error)
}

// UnimplementedOnfidoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOnfidoServiceServer struct {
}

func (*UnimplementedOnfidoServiceServer) GenerateApplicantSDKToken(ctx context.Context, req *ApplicantSDKTokenRequest) (*ApplicantSDKTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateApplicantSDKToken not implemented")
}
func (*UnimplementedOnfidoServiceServer) WebhookPush(ctx context.Context, req *OnfidoCheckWebhookRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebhookPush not implemented")
}

func RegisterOnfidoServiceServer(s *grpc.Server, srv OnfidoServiceServer) {
	s.RegisterService(&_OnfidoService_serviceDesc, srv)
}

func _OnfidoService_GenerateApplicantSDKToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicantSDKTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnfidoServiceServer).GenerateApplicantSDKToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onfido.OnfidoService/GenerateApplicantSDKToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnfidoServiceServer).GenerateApplicantSDKToken(ctx, req.(*ApplicantSDKTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnfidoService_WebhookPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnfidoCheckWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnfidoServiceServer).WebhookPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onfido.OnfidoService/WebhookPush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnfidoServiceServer).WebhookPush(ctx, req.(*OnfidoCheckWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnfidoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onfido.OnfidoService",
	HandlerType: (*OnfidoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "generateApplicantSDKToken",
			Handler:    _OnfidoService_GenerateApplicantSDKToken_Handler,
		},
		{
			MethodName: "webhookPush",
			Handler:    _OnfidoService_WebhookPush_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onfido.proto",
}
