name: Build,Lint and run tests
on:
  push:
    branches:
      - develop
      - staging
      - master

  pull_request:
    branches: [master, staging, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "lint" workflow
  lint:
    name: Lint

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15 # The Go version to download (if necessary) and use.

      # # cache go modules
      # - name: Cache go modules
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      #     restore-keys: ${{ runner.os }}-go-

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup credentials to access private repo
        run: git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      # Run fmt of code
      - name: check formatting
        run: make fmt-check

      # Run vet & lint on the code
      - name: Run code vet
        run: make vet

      # Run vet & lint on the code
      - name: Run code lint
        run: make lint

  # The "TEST" workflow
  test:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lint] # Only run this workflow when "lint" workflow succeeds

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15 # The Go version to download (if necessary) and use.

      # # cache go modules
      # - name: Cache go modules
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
      #     restore-keys: ${{ runner.os }}-go-

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup credentials to access private repo
        run: git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      # Run unit tests + coverage
      - name: Run unit tests
        run: make test

  # The "TEST" workflow
  build:
    name: Build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lint, test]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15 # The Go version to download (if necessary) and use.

          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup credentials to access private repo
        run: git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

        # Run build of the application
      - name: Run build
        run: go build .
