name: Build,Lint and run tests
on:
  push:
    branches:
      - develop
      - master

  pull_request:
    branches: [ master,develop ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Cache go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get and verify dependencies
      env:
        GOSUMDB: "off"
        GOPROXY: "direct"
      run: go mod download && go mod verify

    - name: Check formatting
      run: make fmt-check

    - name: Build app to make sure there are zero issues
      run: go build

    - name: Run go vet
      run: go vet ./...

    - name: Run linting
      run: make lint

    - name: Run all tests
      run: go test -v ./... -cover
